version: "3.9"
services:
  reverse-proxy:
    image: nginx:1.21.6
    container_name: reverseproxy
    ports:
      - 443:443
      - 80:80
    networks:
      - frontend
      - backend-cms
    volumes:
      - ./reverseproxy/logs:/var/log/nginx/
      - ./reverseproxy/certs:/etc/nginx/certs
      - ./reverseproxy/conf:/etc/nginx/conf.d
      - ./reverseproxy/nginx.conf:/etc/nginx/nginx.conf
  cms1:
    depends_on:
      - database
    image: cms
    container_name: cms
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpressmdp
    networks:
      - backend-cms
      - backend-db
    volumes:
      - ./cms/certs/ssl-cert-snakeoil.key:/etc/ssl/private/ssl-cert-snakeoil.key
      - ./cms/certs:/etc/ssl/certs/
      - ./cms/public:/var/www/html/
      - ./cms/sites-enabled:/etc/apache2/sites-enabled
      - ./cms1/logs:/var/log/apache2
  database:
    image: database
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: davidstos
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - backend-db
networks:
  frontend:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1
  backend-cms:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24
  backend-db:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.20.0/24